### ISSUE TITLE
Client logos on the walls

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/lb_breakroom#2]
I think it would be nice to put the client logos on this wall
![janus vr 2015-04-04 18-57-22](https://cloud.githubusercontent.com/assets/28543/6995308/6f691ad6-dafc-11e4-8c34-4462f62e2d6c.png)

**Comment by sirkitree** [comment]
I started, but putting them on a wall that is not on a 90 deg vector is a royal PITA so I'm putting them on this one instead.
![janus vr 2015-04-04 19-18-50](https://cloud.githubusercontent.com/assets/28543/6995359/72e7eb62-daff-11e4-810d-254c650acb16.png)

**Comment by sirkitree** [comment]
Ended up making a contact sheet in photoshop to automate putting all the various logos into one file and placed that.
![janus vr 2015-04-05 08-33-38](https://cloud.githubusercontent.com/assets/28543/6997178/77537058-db6e-11e4-97c6-916f0a2c5bc4.png)

**Comment by davexoxide** [comment]
:+1:
